### ISSUE TITLE
[QUESTION] - Adding bulma extensions

### ISSUE THREAD

**Issue by casalot** [re-fort/vue-webpack-boilerplate#45]
How would I go about adding any of these [bulma extensions](https://bulma.io/extensions/)?

**Comment by casalot** [comment]
Would it be as simple as using [bulma customizer](https://bulma-customizer.bstash.io/), and then adding the exported `.sass` files for the extensions to the [`bulma.sass`](https://github.com/re-fort/vue-webpack-boilerplate/blob/master/src/stylesheets/bulma.sass) from the boilerplate?

**Comment by re-fort** [comment]
Just adding js to [main.js](https://github.com/re-fort/vue-webpack-boilerplate/blob/master/src/main.js) and sass(or css) to [bulma.sass](https://github.com/re-fort/vue-webpack-boilerplate/blob/master/src/stylesheets/bulma.sass)
Note: if bulma extension uses bulma's variable, you have to import file after [importing variables](https://github.com/re-fort/vue-webpack-boilerplate/blob/master/src/stylesheets/bulma.sass#L7).

**Comment by re-fort** [comment]
Closing, feel free to reopen it!
