### ISSUE TITLE
Why don't you have any unit tests?

### ISSUE THREAD

**Issue by mk2** [re-fort/vue-webpack-boilerplate#7]
I want to use this boilerplate to FULL SPEC VUE DEVELOPMENT (with tests).

![giphy-21](https://user-images.githubusercontent.com/747840/28958911-3cb131d2-7933-11e7-89d9-43e9d951e42a.gif)

**Comment by re-fort** [comment]
Thanks.
I intend to add an example for unit testing with Karma + avoriaz + mocha.
I'm gonna use avoriaz until Vue.js official team publishes vue-test-utils beta.

**Comment by re-fort** [comment]
I added a unit test☺️
Changes: #15
